name: Deploy branch to heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checks out repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        run: |
          echo ${{ github.repository }}
